### ISSUE TITLE
Add a way to block the component in a certain state

### ISSUE THREAD

**Issue by iongion** [theKashey/react-imported-component#1]
I do not know how to do-it myself, I arrived here due to `react-loadable` not working with react-hot-loader and this tiny component looks awesome and does the job!
The need is to be able to visually test both cases, for the `LoadingComponent` and the `ErrorComponent`
Also, it would be interesting if these cases could be delayed, `react-loadable` has such a facility, do you think it is good idea to have it here too ?

**Comment by theKashey** [comment]
To "test" loader - just have a look in tests
```js
      const loader = () => Promise.reject('error');
     // block for a while
     // const loader = () => new Promise( (resolve, reject) => setTimeout(reject, 10000);
     // const loader = () => new Promise( (resolve, reject) => setTimeout(()=>resolve(requre('fileName'), 10000);
     // block forever
     const loader = () => new Promise( () => {} )
      const wrapper = mount(<HotComponentLoader
        loader={loader}
        ErrorComponent={ErrorComponent}
      />);
      expect(wrapper.find(LoaderComponent)).to.be.present(); // load on mount
      setImmediate(() => {
        expect(wrapper.find(ErrorComponent)).to.be.present(); // error after promise Resolve.
      });
```

About delay - it is a good point. I did not add that feature cos this is not a Loader duty, but I should have some delay, at least 1ms(to handle async nature of a Promise). But when you have 1ms delay - you can have 100ms delay. No difference.

Until then, or in case you have your own Loader component - you can use [react-delay](https://www.npmjs.com/package/react-delay), or [react-delay-render](https://www.npmjs.com/package/react-delay-render).
