### ISSUE TITLE
Server-side rendering components that fetch data asynchronously

### ISSUE THREAD

**Issue by krazyjakee** [theKashey/react-imported-component#11]
I have components that request data from third party endpoints to populate the initial state via ajax.

With the workflow this library provides, how can the server perform these requests when rendering the components server-side then provide that data to the client and prevent an unnecessary AJAX request in the browser?

It's complicated to explain, please let me know if you need more information.

**Comment by theKashey** [comment]
Bad news - this library could not help you.
1. The "usual" workflow is to use Redux to store application state, and prepopulate state on frontend.
2. You could not perform ajax calls from React during server-side rendering, as long calls async, while render is sync.
3. If you are making the "ajax" call before the render - goto .1

**Comment by theKashey** [comment]
I think the best way to handle this in a future - use __suspence__. Right now [loadable-components](https://github.com/smooth-code/loadable-components) are the only library, which could handle it.
I am going to provide necessary API's to this library.

The second approach is to use [react-async-bootstrapper](https://github.com/ctrlplusb/react-async-bootstrapper) + [react-async-component](https://github.com/ctrlplusb/react-async-component)

The third variant, might be most "maintainable",- https://github.com/faceyspacey/redux-first-router + any loader.

**Comment by EdonGashi** [comment]
If you are using Koa in your server node-fibers may have potential for this task https://github.com/laverdet/node-fibers.

I managed to get this working by doing something like this (pseudocode):

```js
middlewares = [
  fiberMiddleware,
  renderMiddleware
]
```
where
```js
function fiberMiddleware(ctx, next) {
    return new Promise(function (resolve, reject) {
      ctx.fiber = Fiber(function () {
        const current = Fiber.current
        next()
          .then(result => {
            current.run()
            resolve(result)
          })
          .catch(error => {
            current.run()
            reject(error)
          })
        Fiber.yield()
      })

      ctx.fiber.run()
    })
  }
}
```

The beauty of koa is that you can handle both the "before" and "after" part of the middleware chain, which means that the render process is wrapped inside a fiber. What I did next was create an attribute `@tracked` which does nothing (forwards the call) client-side but when executed on the server pauses current fiber until the returned promise finishes. Example:

```
class MyStore {
  @tracked async getData() {
    await fetch(...)
  }
}

class MyPage {
  componentWillMount() {
    // Runs asynchonously in client, but synchronously in server!
    myStore.getData()
  }
}
```

The implementation of tracked pauses Fiber.current when the call starts, which means that the render process is frozen at that componentWillMount above until the promise is resolved, and afterwards the fiber is resumed and the render process continues. Cwm is just an example, you should probably have a router layer for this sort of work.

If you have more than one async frame (fire and forget) you need to hold a counter with context or some sort of state management, and resume when all calls have resolved.

I haven't accomplished anything with this approach yet, just sharing the idea I had.

**Comment by theKashey** [comment]
Yeah, but this library tracks used components using a single global variable, and will blow up with any async rendering :(

**Comment by EdonGashi** [comment]
Would a context mechanism help to isolate state from global to the component tree? Other libs like react-universal-component allow this:

```
<ReportChunks report={chunkName => chunkNames.push(chunkName)}>
    <App />
</ReportChunks>,
```

**Comment by theKashey** [comment]
You are absolutely right.The only issue to solve - pick the right form for an API.

**Comment by theKashey** [comment]
```js
let streamUID = 0;
const html = renderToString(
  <ImportedStream takeUID={uid => streamUID=uid}>
    <YourApp />
  </ImportedStream>) + printDrainHydrateMarks(streamUID);
```
A new component - `ImportedStream` to separate rendering streams
