### ISSUE TITLE
Warning: Did not expect server HTML to contain a <div> in <div>.

### ISSUE THREAD

**Issue by lukebarton** [theKashey/react-imported-component#12]
I get this error when I use `importedComponent` and `hydrate()` to do SSR hydration. Both the SSR html and hydrated html appear identical and I do not get any error if I import the component normally.

```js
const element = document.getElementById("app");
const app = (
  <Provider store={store}>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </Provider>
);

// In production, we want to hydrate instead of render
// because of the server-rendering
if (window.___REACT_DEFERRED_COMPONENT_MARKS) {
  // rehydrate the bundle marks
  rehydrateMarks().then(() => {
    ReactDOM.hydrate(app, element);
  });
} else {
  ReactDOM.render(app, element);
}
```

```js
const Another = importedComponent(() => import("./components/Another"));
// import Another from "./components/Another";

export default function App() {
  return (
    <div>
      <Helmet defaultTitle="Hello World!">
        <meta charSet="utf-8" />
        <link rel="icon" href={favicon} type="image/x-icon" />
      </Helmet>
      <Switch>
        <Route exact path="/" component={Home} />
        <Route exact path="/another" component={Another} />
        <Redirect to="/" />
      </Switch>
    </div>
  );
}
```
```js

export default function generateHtml(markup, state) {
  // Get the serer-rendering values for the <head />
  const helmet = Helmet.renderStatic();

  const $template = cheerio.load(HTML_TEMPLATE);
  $template("head").append(
    helmet.title.toString() + helmet.meta.toString() + helmet.link.toString()
  );
  $template("head").append(
    `<script type="text/javascript">window.__PRELOADED_STATE__ = ${JSON.stringify(
      state
    ).replace(/</g, "\\u003c")};</script>`
  );
  $template("head").append(printDrainHydrateMarks());
  $template("#app").html(markup);

  return $template.html();
}
```

**Comment by theKashey** [comment]
What is inside `window.___REACT_DEFERRED_COMPONENT_MARKS`? Did it track loaded components properly? (babel plugin is required for this operation)

You can try to _emulate_ babel plugin, like I did in [tests](https://github.com/theKashey/react-imported-component/blob/master/_tests/rehydrate.spec.js#L21)
```js
  function importedWrapper(marker, name, realImport) {
    return realImport;
  }

 const Another =  importedComponent(() => importedWrapper('components/Another', 'mark1', import("./components/Another"));
```

**Comment by theKashey** [comment]
Any example to reproduce?
Could you add some random `data-rnd` attributes to random divs to figure out which one React don't like.

**Comment by lukebarton** [comment]
https://www.dropbox.com/s/ha8g3hgvs9jkg21/smsc.zip?dl=0
```sh
$ yarn install
$ webpack
$ node dist/server/index.js
```
should do the trick

**Comment by theKashey** [comment]
This is related to React 16.3
I've just updated dependencies and get the same.

**Comment by theKashey** [comment]
I've fixed the actual problem, but this warning is still exists.
And I am not sure why. HTML before and after hydration is the same.

**Comment by lukebarton** [comment]
The HTML (for me) has always been the same before and after. That's why I
raised this issue.

Are you sure the things you have changed are actually related, if the
warning still persists?

**Comment by theKashey** [comment]
There was a flickering of async component, I saw it, and I debug it - application was not waiting for `Another` to be loaded. This is the thing I've fixed.
But still getting the error, regardless of Another position, but only when it exists.

I have to dig deeper.

**Comment by theKashey** [comment]
I've found an issue. React 16.3 deprecated componentWillMount, and this changed the way Loader work.
Will fix tomorrow. It is much harder to write enzyme test to catch it, that to fix it.

**Comment by theKashey** [comment]
The problem was `hydrate` itself.
If component was _preloaded_ it will be _reused_ on Loader creation, but the actual value will be set using setState.
This is ok for enzyme or frontend, as long setState inside contructor or lifeCycle method will lead to the `right` state used in render.

In case of hydrate, look like this is bound to 16.3, "the current state" will be used on render. And it was just empty, resulting wrong rehydration.
Wrong but invisible for the eye, as long correct state was already state, and changes will be applied before browser redraw.

**Comment by theKashey** [comment]
v4.3.1

**Comment by jazblueful** [comment]
@theKashey I'm getting the exact same behavior on react 16.8.6 and react-imported-component 5.5.3

Did you fix this or is it something I can safely ignore as long as there is no apparent mismatch between server rendered and hydrated markup?

Thank you

**Comment by theKashey** [comment]
This message from react is just about unexpected difference between server and client rendered code. Like - just don't match, by any reason.

Please look at your HTML coming from server, and the result HTML in the browser. That's the difference. Then we might think about "why".

If you have some example I could play with - just sent me a link, and I would handle the rest.

**Comment by jazblueful** [comment]
Well I have a monorepo and the concerning package is difficult to separate from the rest.

I can easily see what the server sends, but what is the proper way to extract the final js hydrated html? I copied outerHtml from the render/hydration root div and the server response into diff tool and there was no difference.

**Comment by jazblueful** [comment]
I think I'm doing something fundamentally wrong with react-imported-components. When I export component to be loaded by react-imported-component:

```js
const Test = () => 'test';

export default Test;
```
and re-export it as a route component:
```js
import importComponent from 'react-imported-component';

const Test = importComponent(() => import(/* webpackChunkName: "test-component" */ './TestComponent'), {});

const TestRoute = {
  component: <Test />;
}

export default TestRoute;
```
App component used with hydrate:
```js
import { Grommet } from 'grommet';

const App = ({children}) => (<Grommet theme={customTheme} full>{children}</Grommet>);

export default App;
```
client.js
```js
import ReactDOM from 'react-dom';
import { rehydrateMarks } from 'react-imported-component';
import route from './TestRoute';
import App from './App';

const app = <App>{route.component}</App>

rehydrateMarks().then(ReactDOM.hydrate(app, document.getElementById('root'));

```

I Get server rendered html:
```html
<div id="root"><style data-styled="cqQlmF" data-styled-version="4.3.2" data-styled-streamed="true">
/* sc-component-id: sc-global-552078406 */
/* styled-components styles... */
</style><div class="StyledGrommet-sc-19lkkz7-0 cqQlmF">test</div></div>
```

Final html after rehydrateMarks().then(ReactDOM.hydrate()):
```html
<div id="root"><div class="StyledGrommet-sc-19lkkz7-0 cqQlmF">test</div></div>
```

And console output:
```
Warning: Did not expect server HTML to contain the text node "test" in <div>.
```

Client App and ssr live in 2 separate packages. When client is built with webpack, it builds a version for browser (code splitting enabled) and a version with target: 'node' (1 bundle) for inclusion by ssr which sends the rendered html down to the client as a stream together with interleaveWithNodeStream from styled-components.

**Comment by theKashey** [comment]
You shall compare content of “root” element just before hydration, and just after.
I am not sure that’s the problem, as long as “test” should be expected to be inside the only rendered div.
Could you share the problematic example, or just  final bundles to play with?

**Comment by jazblueful** [comment]
I replaced
```js
rehydrateMarks().then(ReactDOM.hydrate(app, document.getElementById('root'));
```

with:
```js
rehydrateMarks().then(() => {
  ReactDOM.hydrate(app, document.getElementById('root'));
});
```

The warning is now gone and most importantly the flicker when hydrating, is gone as well.

Thank you :)

**Comment by theKashey** [comment]
😅of course, you were calling hydrate too early.
