### ISSUE TITLE
What is __deoptimization_sidEffect__? Possible typo?

### ISSUE THREAD

**Issue by swernerx** [theKashey/react-imported-component#14]
Hi! just stumbling through your code to figure out if I like to replace universal component. I am wondering about two things:

1. What is `__deoptimization_sidEffect__` where is this coming from. It seems to be checked for, but is never assigned anywhere. Googling it also did not work. Also seems to be a small typo involved. Shouldn't it be called `__deoptimization_sideEffect__`?
2. Is this really in any way specific to React? Wondering about whether it supports other frameworks as well. Even basic things like Preact.

Thanks!

**Comment by theKashey** [comment]
This is typo, and this is "deoptimization" "sideEffect". Preventing production mode to optimize this function, which took 3 arguments and returning 1, from being optimized to the "nothing".

See https://github.com/theKashey/react-imported-component/issues/13
