### ISSUE TITLE
Using lazy from react-imported-component doesnt show fallback while loading

### ISSUE THREAD

**Issue by taikn** [theKashey/react-imported-component#141]
Please see the following codesandbox:
https://codesandbox.io/embed/reactlazy-vs-react-imported-component-lazy-tnshj

**Comment by theKashey** [comment]
Plus documented `Lodable.resolution` in the README. Thank you for spotting such a big problem.

**Comment by taikn** [comment]
Wow, amazing, thank you for a quick fix!

**Comment by theKashey** [comment]
I was going to announce a new version `imported` next week, and you just saved my butt. Thank you :)
