### ISSUE TITLE
Import Limitations

### ISSUE THREAD

**Issue by theKashey** [theKashey/react-imported-component#147]
> react-imported-component: no mark found at XXX. Please check babel plugin or macro setup, as well as imported-component's limitations.

The problem - RIC could not found _trackable mark_ inside a given `importer` function. This could be due to 3 reasons:
- there is no `dynamic import` inside
- the `import` is not "visible" in the `importer` source code.
- there is a problem with babel plugin or babel macro, so RIC could not inject required mark

## there is no `dynamic import` inside
We don't know which `importedComponent` you might need, and don't known which one you have used - it's hard to create similarities between Server-Side bundle, and the Client-Side one.
We track __only__ `dynamic imports`, and if you haven't used them - tracking is doomed. Hower, __you might inject your own mark__ - `importedMark("imported_UNIQUE_MARK_component")`, and, to be honest, only __text__ matters.

## the `import` is not "visible" in the `importer` source code.
We are tracking `marks` by matching `importer.toString` against RegExp. If `import`(or mark injected manually) is not visible in the importer source code - we could not see it.

```js
// works
importedComponent(() => DoWhetEverYouWant(() => import().then(...));

// doesn't work
const importPage = () => import('page');
importedComponent(() => DoWhetEverYouWant(importPage);
```

## there is a problem with babel plugin or babel macro, so RIC could not inject required mark
To get it working you need:
- or babel plugin enabled for all files with "imports"
- or `react-imported-component/macro` imported in files with "imports" (and babel-plugin-macro)

you don't have to wrap imports with `imported`, `lazy` and so on - just make sure they will be transpiled. See our CRA example.

**Comment by vinicri** [comment]
Hi, I'm getting this 

`react-imported-component: no mark found at [Function] Please check babel plugin or macro setup, as well as imported-component's limitations. See https://github.com/theKashey/react-imported-component/issues/147`

but aparently ssr is all good. Is there any docs that clarify the concept of marks above. I'm not really getting it.

**Comment by theKashey** [comment]
Every `import` got a "mark" via babel plugin, which is basically crc32 from the absolute file path.
`import(someFile)` -> `helper("mark", import(someFile)` -> `mark`

If you are importing something, which does not have "import" in the function body - imported is not able to find a mark

✅
```js
imported((() => import('file'));
imported((() => { someLogic(); return import('file')});
```

⛔️
```js
imported((() => someLogic());
imported((() => { someLogic(); return notARealImport('file')});
```

However there are use cases when you don't need and don't have "import" (and so mark).

----

However it seems to be that in this case the error is in another place - `react-imported-component: no mark found at [Function]` -> `[Function]` should be a function body, but it's not "stringified" by a some reason.
Any idea why?

**Comment by vinicri** [comment]
I'm wrapping the `importedComponent`, I think that might be the issue

`
export const getLoadable = (importPromise, loadingComponent) => {
  return importedComponent(() => importPromise, {
    LoadingComponent: loadingComponent || (() => <div/>)
  })
}
`

I call it with `getLoadable(import('...'))`

**Comment by vinicri** [comment]
It's gone doing this instead

```javascript
export const getLoadable = (importFunction, loadingComponent) => {
  return importedComponent(importFunction, {
    LoadingComponent: loadingComponent || (() => <div/>)
  })
}

getLoadable(() => import('...'))
```

**Comment by theKashey** [comment]
Yep, this is the correct way to import things, in your old code you were kicking off __all imports__ on application start.

**Comment by vinicri** [comment]
Thanks

**Comment by MuhammadSawalhy** [comment]
I am getting this issue when the frontend server is down. Netlify sometimes goes down, when I first opened the home page, and after a while, I navigated to an imported route's component, suddenly everything on the page disappeared and I got this error message in the console.

```
react-imported-component: no mark found at [Function] Please check babel plugin or macro setup, as well as imported-component's limitations. See https://github.com/theKashey/react-imported-component/issues/147
```
