### ISSUE TITLE
Problem with babel-plugin-macros

### ISSUE THREAD

**Issue by ludbek** [theKashey/react-imported-component#156]
I am getting following error with `"react-imported-component": "^6.2.0"` .
Manually installing `babel-plugin-macros` does solve the issue.

```
node_modules/react-imported-component/dist/es2015/macro.js:1:28: Cannot resolve dependency 'babel-plugin-macros'
> 1 | import { createMacro } from "babel-plugin-macros";
```

**Comment by theKashey** [comment]
It was more about - why would you use babel-macros if you don't "need" them?
Anyway, I'll add `babel-plugin-macros` as a dependency
