### ISSUE TITLE
Upgrading to 6.2.0 shows a warning

### ISSUE THREAD

**Issue by ludbek** [theKashey/react-imported-component#158]
Upgrading `react-imported-component` from `5.3.0` to `6.2.0` shows following warning

```
loadable.js:120 react-imported-component: no mark found at ƒ (){return require("_bundle_loader")(require.resolve("./pages/About"))} Please check babel plugin or macro setup, as well as imported-component's limitations. See https://github.com/theKashey/react-imported-component/issues/147
```

I have been following this post https://hackernoon.com/move-over-next-js-and-webpack-ba367f07545 .  Its code base can be found here https://github.com/patrickleet/streaming-ssr-react-styled-components .

The repo works perfectly. I upgraded all the packages there and got the warning above.

**Comment by theKashey** [comment]
This message was not sent in the previous version, however really - there is no mark present in the source code. That means babel plugin is not working.

## How to fix
Hoist it in the `.babelrc`
```diff
{
+  "plugins": [
+    ["react-imported-component/babel"]
+  ],
  "env": {
    "test": {
      "presets":[
        ["@babel/preset-env"],
        ["@babel/preset-react"]
      ],
      "plugins": [
        ["@babel/plugin-syntax-dynamic-import"]
      ]
    },
    "server": {
      "plugins": ["react-imported-component/babel", "@babel/plugin-syntax-dynamic-import"]
    },
    "client": {
      "plugins": [
        ["react-imported-component/babel"]
      ]
    }
  }
}
```
or find why enviroment is not set properly

**Comment by theKashey** [comment]
PS: And thank you for the article 👍

**Comment by ludbek** [comment]
Thanks for quick responses.
