### ISSUE TITLE
Typescript definition error with newest react typescript definition

### ISSUE THREAD

**Issue by akonyer** [theKashey/react-imported-component#18]
ERROR in [at-loader] ./node_modules/react-imported-component/module.d.ts:20:88
    TS2315: Type 'ReactNode' is not generic.

Looks like ReactNode does not have a generic definition in the react definition file. Maybe it used to in a previous version.

**Comment by theKashey** [comment]
My bad. Have no idea why TS example did work.

**Comment by theKashey** [comment]
Fixed in 4.4.1.
