### ISSUE TITLE
importing a js file lazily in the code throws bind undefined error

### ISSUE THREAD

**Issue by intelcoder** [theKashey/react-imported-component#193]
I am not 100% this issue is caused by react-imported-component.

Component loading works perfectly. However, when I try to import a redux file. it logs 

**Cannot read property 'bind' of undefined**

they way I import a js file is like this

`  const a = yield call(() => import(/* webpackChunkName: "test-test-test" */ 'Modules/user/module'))`

Do you think it is related to the library?

**Comment by theKashey** [comment]
Should not be related - there is no real transformation applied to `import`.
Could you please share a bigger error - it should have a code snippet around, which might help understand the problem.

**Comment by intelcoder** [comment]
I just changed all the bind to arrow function and now it works.
