### ISSUE TITLE
Preload CSS of lazy loaded components

### ISSUE THREAD

**Issue by Tarvald** [theKashey/react-imported-component#196]
Hi,
I am trying to implement react-imported-component in our project. It is large e-commerce platform.
However, one of lazy-loaded components (top bar) has a glitch on page load.
It appears (because of delivered html via SSR) before CSS are loaded, so I can see it unstyled for 1s - 2s.

Webpack automatically split all css also to chunks as webpack did with components.

Am I doing something wrong?

**Comment by theKashey** [comment]
Yeah. Out of the box only JS is handled, as long as it's not a big deal to defer hydration till all the scripts got ready. If you need CSS, not not using CSS-in-JS which usually handles SSR via inlining used styles (aka critical), then you have to add some code.
There are two ways to solve the problem:
- add required CSS files into the return HTML, so it will be there when needed
- inline used CSS, so you will not miss any style needed
- Methods could be combined

### Add required CSS files
For this task I use [webpack-imported](https://github.com/theKashey/webpack-imported). It's working in 3 steps:
- add webpack plugin (to generate stats)
- collect used "marks" from `imported-component`
- render scripts and styles using provided components ("separation", like only styles, is not supported)

There is example in [this project's readme](https://github.com/theKashey/react-imported-component#via-webpack-imported)

> note: this API does not support stream rendering out of the box

### inline used CSS
[used-styles](https://github.com/theKashey/used-styles) is almost zero configuration "critical css" extraction. The styles required to render the page would be just there.

> this one can be stream friendly, but there are complications

**Comment by Tarvald** [comment]
@theKashey 
Used-styles solved my problem out of the box.
Thanks a lot!
