### ISSUE TITLE
babel-preset-latest deprecated

### ISSUE THREAD

**Issue by mgreer** [theKashey/react-imported-component#20]
`babel-preset-latest` is deprecated in favor of `babel-preset-env`. It is throwing errors for me, and likely others, so should move .babelrc to
```js
{
  "presets": ["env","react"],
  "plugins": ["transform-class-properties","dynamic-import-node"]
}
```

and package.json to:
```js
    "babel-preset-env": "^6.24.1",
```

**Comment by theKashey** [comment]
Fixed.
