### ISSUE TITLE
Can I use ssr without nodejs?

### ISSUE THREAD

**Issue by artemkliaus** [theKashey/react-imported-component#207]
Hello! Please, help me, can I use this package without nodejs on a backend? I have clear V8 engine for render pages and cannot configure webpack with "target": "node". Thanks!

**Comment by theKashey** [comment]
Can shed more light? What you have and what you can use?
Library itself is not bound to the "node" and can work even in a browser ([react-snap](https://github.com/theKashey/react-imported-component/tree/master/examples/hybrid/react-snap)).

So what are your conditions?
