### ISSUE TITLE
[DISCUSSION] Don't Understand the Magic Comment

### ISSUE THREAD

**Issue by do-kevin** [theKashey/react-imported-component#208]
Hey there,

I don't quite understand what I should be doing with this "magic" comment:
```
// all, even the ones you tried to hide in comments (that's the cost of making a very fast parser)
// to remove any import from here
// 1) use magic comment `import(/* client-side */ './myFile')` - and it will disappear
```
in my `imported.ts`.  It auto-generates `[() => import(/* client-side */'./myFile'), '', './src/myFile', true]`. 

My app encounters an error trying to find `myFile`. I don't know what I should do with the magic comment, so I just end up just making a dummy TSX file called myFile for it.

Thanks

**Comment by theKashey** [comment]
🤦‍♂️so there is a comment that imported will discover any "imports", even in comments, and there is a way to hide them for such situations.... and it causes imported to see that import.

There is two problems here:
- imported should ignore imported file. This [code exists](https://github.com/theKashey/react-imported-component/blob/master/src/scanners/scanForImports.ts#L122) and by fact is working. __But not for you__.
- imported should really ignore imports marked as `/* client-side */` - code for it [also exists](https://github.com/theKashey/react-imported-component/blob/master/src/scanners/scanForImports.ts#L95), but does a little different thing

Right now the only working way to "remove" import is to use `testImport` via `.imported.js` configuration file.

**Comment by do-kevin** [comment]
Haha, sorry for the facepalm. I understand now. I was confused by `// generated by react-imported-component, DO NOT EDIT` and when it generated `[() => import(/* client-side */'./myFile'), '', './src/myFile', true]`.
