### ISSUE TITLE
useImported on testing with react testing library

### ISSUE THREAD

**Issue by intelcoder** [theKashey/react-imported-component#209]
I have this kinda import in one of the sub component.

```
const { imported: sheet } = useImported(() => import(/* webpackChunkName: "spritesheet" */'Static/spritesheet.json'))
```

When I render with react testing library, it keep complain like
```
You should `await whenComponentsReady()
```

I tried to wait for that but it did not solve the issue

Thank you

**Comment by theKashey** [comment]
There are two steps:
- "node" environment should be properly detected. If you see a "you should" message - that means it's working.
- `beforeAll(() => whenComponentsReady())` should defer tests till they are ready to be executed.

**Comment by intelcoder** [comment]
I see. It works fine. Thank you for the answer
