### ISSUE TITLE
Async non-components modules

### ISSUE THREAD

**Issue by Tarvald** [theKashey/react-imported-component#223]
Hi, 
In readme I can see that this library does not support `import(./${value})`. So, can I somehow lazy load normal javascript modules, what we normally import by `import * from '...'`?

Best regards

**Comment by theKashey** [comment]
Absolutely. There are two ways of doing it:
- component approach, similar to [loadable-components/lib](https://loadable-components.com/docs/library-splitting/). See https://github.com/theKashey/react-imported-library
- [hook](https://github.com/theKashey/react-imported-component#hook). `useImported` can import absolutely anything, except "non static imports"(ie `import(./${value})`)

**Comment by Tarvald** [comment]
Thanks a lot! 
I am starting doing that right away in hope that it will decrease size of our main bundle file :)
