### ISSUE TITLE
Using react-imported-component with react 18

### ISSUE THREAD

**Issue by KoderFPV** [theKashey/react-imported-component#228]
Hi,

Do you know guys if this library still needed in react 18? We are during migration process to R18 and we wonder if we should replace this library with react 18 native lazy loading support, what we allready attempt, but with no success :)

**Comment by theKashey** [comment]
React 18 can "hold" information inside Suspense boundaries while code is loading, but any update will invalidate it. It is very low-level behavior and I would not rely much on in - https://github.com/facebook/react/issues/22692

However if you don't use SSR - then it's totally not a problem, and if you don't use `useImported` - moving to `Lazy` would basically change nothing, just one library less to load.

Hey, there is no such thing as "native lazy loading" - it's only about Suspense and everything else does not matter that much.

**Comment by theKashey** [comment]
Always at your service
