### ISSUE TITLE
react imported component and future upgrades

### ISSUE THREAD

**Issue by KoderFPV** [theKashey/react-imported-component#230]
Hi,

Is it any plan to release a new version of this library someday? It's one of the oldest library in my project and I wonder what to do with that :) Does it even need updates?

Thanks

**Comment by theKashey** [comment]
I might add a few helpers to allow some fancy/handy operations, but so far it's just working. 
Was thinking about allowing wildcard imports via eslint plugin "expanding" the code to make it explicit and TS compatible.

But that's all - nothing planned for the core functionality.

**Comment by KoderFPV** [comment]
Okay, I can confirm that it's working flawlessly in our large e-commerce platform for 3 years already, with no problems at all. 

It has problems with TS types from React 18. ImportedController and ImportedStream components do not have children types which is required in R18 but is not a big deal. 

Also we thought that this library will be no longer required after migration to R18, but that is not true, what you @theKashey  pointed [here](https://github.com/theKashey/react-imported-component/issues/228) and also here(https://github.com/gregberge/loadable-components/issues/994#issuecomment-1899432696)

Also, we try to migrate from renderToString to streams but with no success. In the past, we thought this library was a blocker but now we think is still a problem with React itself, or with our extremely large codebase.

So @theKashey  thank you so much, for your work on lazy/async imports in general for react community

**Comment by theKashey** [comment]
@KoderFPV - I'll look into type issue but R18 streaming is a little more complicated problem - even [emotion hasn't figured it out](https://github.com/emotion-js/emotion/issues/2800)

**Comment by KoderFPV** [comment]
ok, thanks!
I will follow React Community to be updated with streams. 
Also, our team will make more attempts someday to implement it
