### ISSUE TITLE
Uncaught (in promise) ReferenceError: module is not defined with VITE

### ISSUE THREAD

**Issue by ujjwalbanka** [theKashey/react-imported-component#231]
Hi, 
I am converting my React project to VITE instead of Webpack. 
While running the application I am getting an error 
` ReferenceError: module is not defined`

On further debugging, I found that this package is looking for modules.hot and modules are not defined. 
Looking for some help here 

"react-imported-component": "^6.5.3"

<img width="1728" alt="Screenshot 2024-03-15 at 7 21 36 PM" src="https://github.com/theKashey/react-imported-component/assets/7422582/08a05905-a737-4c22-bc23-073794221d67">
<img width="657" alt="Screenshot 2024-03-15 at 7 33 51 PM" src="https://github.com/theKashey/react-imported-component/assets/7422582/4aedbd35-02ae-41b4-9af7-dd3e4426510a">

**Comment by theKashey** [comment]
yep, typeof guard is missing.

**Comment by theKashey** [comment]
Should be solved in v6.5.4
