### ISSUE TITLE
Loadable promise and resoultions properties, problem on CI with jest.js snapshots

### ISSUE THREAD

**Issue by KoderFPV** [theKashey/react-imported-component#234]
Hi, 
We have a strange problem with lazy-loaded components 
![image](https://github.com/theKashey/react-imported-component/assets/7673542/fd7bd23e-29df-4fdc-90b4-dcb9a513d503)

On our CI system, we always have problems where promise property and resolution property wanna be extended with symbols in jest snapshot
However, it does not happen at all on any of our localhosts (of 5 developers)

We have the same node version both on CI and localhosts. 
I noticed that the both properties comes from InnerLoadable

![image](https://github.com/theKashey/react-imported-component/assets/7673542/340f00e3-c1a2-41c4-b0e0-c1bb7509f443)
https://github.dev/theKashey/react-imported-component

@theKashey do you know why it happens maybe? :)

**Comment by theKashey** [comment]
Not sure, but this is how resolved and unresolved promises might look like after serialisation.
I would strongly propose not to snapshot internals of any component you do not directly control, as they can change at any time. 
In turn you are snapshoting Symbols from node internals, so your inability to reproduce the problem on local can be bound to:
- different node versions
- different machine speed

I urge you not even try to resolve the problem and remove the test.

**Comment by KoderFPV** [comment]
I am glad that I asked, I already spent a few hours on it, but I am not going to spend any minute more. :)

However, we are talking quite a lot of jest.js snapshots of components. 
The only that comes into my mind is pollyfil lazy import to fragments as it happens on SSR.

@theKashey what do you think? Could you advice me how to do `monkey patch` lazy as it is on SSR?

**Comment by theKashey** [comment]
In such case you can try [expect.addSnapshotSerializer](https://jestjs.io/docs/expect#expectaddsnapshotserializerserializer) to "collapse" information about lazy component to something simple.
```tsx
expect.addSnapshotSerializer({
  test:(val) => val.replaceImportFunction, // unique enough?
  print:(val) => `imported-components(${val.importer})` // not sure it would print something valuable
})
```
You can do this via jest config, jest setup or per every file as required.

**Comment by KoderFPV** [comment]
@theKashey ok thanks! Will do soon :)
