### ISSUE TITLE
Webpack issue

### ISSUE THREAD

**Issue by joseph-vedadi** [theKashey/react-imported-component#28]
I have a huge list of components which I would love to use your tool with
I am using ejected "create-react-app 
So basically I have a huge menu and want to import components when the user goes to that page 

I have 
```js
this.components = new Map([
      [
        "Statistic_Report",
        importedComponent(() =>
          import("../Components/Statistic_Report/StatisticReport")
        )
      ],
      [
        "Field_Test/Drive",
        importedComponent(() =>
          import("../Components/Statistic_Report/StatisticReport")
        )
      ],
      [
        "Field_Test/Walk",
        importedComponent(() =>
          import("../Components/Statistic_Report/StatisticReport")
        )
      ]
    ]);
```
and I get this error 
```js
TypeError: Object is not a function. (In 'Object(__WEBPACK_IMPORTED_MODULE_0_react_imported_component__["importedComponent"])', 'Object' is an instance of Object) (attached the image)
```
![screen shot 2018-09-27 at 3 32 27 pm](https://user-images.githubusercontent.com/17168374/46178191-b55ea200-c26a-11e8-9f07-666cbb2baa27.png)

Also, I tried to use your example 
```js
const myImportFunction = () =>
      import("../Components/Statistic_Report/StatisticReport");
    this.NewComponent = importedComponent(myImportFunction);
```

![screen shot 2018-09-27 at 3 36 04 pm](https://user-images.githubusercontent.com/17168374/46178288-11c1c180-c26b-11e8-9fc6-a0ade696fcfb.png)

**Comment by Joojoo1020** [comment]
also I added : 
"babel": {
    "presets": [
      "react-app",
    ],
    "plugins":["react-imported-component/babel"]
  },
 to my package.json same thing

**Comment by theKashey** [comment]
Look like `import importedComponent from 'react-imported-component';` is not working.
could you just before the error write `console.log(importedComponent)`. Just wondering what is inside.

**Comment by theKashey** [comment]
How it's going?
