### ISSUE TITLE
CPU goes high with HMR after update to 2.0.0

### ISSUE THREAD

**Issue by nelsondaza** [theKashey/react-imported-component#3]
I did update to 2.0.0 and now my components don't stop rendering after HMR, I think the connected components are the problem but not very sure.

My Chrome tab gets to 90+% CPU, go back to 1.0.4 solved.

Is it just me?

**Comment by theKashey** [comment]
2.0.0 changed the way it detects HMR event. Might be I've missed something.

**Comment by theKashey** [comment]
2.0.0 got a bug with "classical" React-Hot-Loader v3
Use React-Hot-Loader v4 ("@next"), or bump this library to the version 2.0.1

Thank you for reporting an issue, I will never spot it, as long I am using RHL v4.

**Comment by nelsondaza** [comment]
@theKashey that was awesomely fast. Updating to 2.0.1 made it work like a charm.
Really appreciated the help.

**Comment by theKashey** [comment]
You are welcome. Thats my fault that this library, which supposed to solve some issues of RHLv3, was tested agains v4.

**Comment by nelsondaza** [comment]
Hi, I didn't realise it before but some of my "simple" components are not hot loading, updating to RHL V4 does not fix it.
If you need more info I'll be glad to help.

**Comment by theKashey** [comment]
I'll ask for the sources then. V4 should almost always work.

**Comment by nelsondaza** [comment]
Hi,
Sorry about the late. It is now working fine, after updating some libs, I think, but don't really know which ones.

This one is a great package, thanks for all the help.
