### ISSUE TITLE
Interesting Parcel project issue

### ISSUE THREAD

**Issue by krazyjakee** [theKashey/react-imported-component#4]
Please check out the code-splitting branch of my fork here: https://github.com/krazyjakee/parcel-react-ssr/

Specifically my last commit where I try to add this library to render the components on the server: https://github.com/krazyjakee/parcel-react-ssr/commit/c43811eedbca2cd51e0303d4dd889c57559760cc

I have followed the instructions but cannot understand why the components don't render. All I see is the list of markers.

**Comment by theKashey** [comment]
Your code seems to be ok. Let me check what is wrong.

**Comment by theKashey** [comment]
Your example is perfectly working for me. Visually. Both for dev and SSR modes.

But - `rehydrateMarks` by fact does nothing - it could not found a __mark__ to rehydrate, and not preloading async chunk before react `hydrate` (causing "blink")
Something like _today_ I am going to publish a new minor version, which changes the SSR approach. It will fix everything for any bundler you may use(thats the goal).

**Comment by krazyjakee** [comment]
To clarify, I see the client render too, but in view-source://localhost:1234/codeSplit, I don't see the script/link tags for additional css/js and the html that makes up the page.

I'll wait for your change and try again with any new logic. Thanks so much for your reply!

**Comment by theKashey** [comment]
There will be no additional scripts on the page. "Translating" the imports into bundler specific files is a dead end.
React-imported-component repeats the `imports` you wrote in your code. From one point of view - it will delay loading by one "hop", requiring main bundle to be loaded in front, but from another - it will just work with parcel, not only with webpack, as usual.

**Comment by theKashey** [comment]
All "SSR-Aware" loaders could do this. They will keep your pre-rendered content unchanged unless they will be fully prepared to replace(rehydrate) it.
But usually you have to _kick_ loader into this waiting. Here this command names `rehydrateMarks`, and it is broken a bit for parcel.

**Comment by theKashey** [comment]
Ok, it lead to the major version change.
v4 just got published, and __your__ example was used as example :)

Could confirm that everything works just perfect.

**Comment by krazyjakee** [comment]
Oh wow, such an honor thank you 💃 !

I will check this out tonight. I mean, this is something quite special really. SSR, code-split react with  fast compilation and zero configuration... very cool.

**Comment by theKashey** [comment]
Not zero :)
