### ISSUE TITLE
Pre-load webpack chunks via initial html

### ISSUE THREAD

**Issue by wmertens** [theKashey/react-imported-component#42]
Right now, the hydration waits for the components to be loaded, which fires off the requests for the required JS files.

However, this means that those files are only requested once all the initial JS was downloaded and parsed. It would be nice if the required JS files are already marked in the initial HTML.

To do so, the marks array has to be converted to a list of client JS files on the server, and then added as `<script src/>` tags.

I think a possible approach would be to use a regex to scan all client JS files at server start, so that it is independent of the used bundler or chunking. It only needs to make sure it's scanning JS files from the current build (use an assets array), and the regex should only match the definition of the components, not the imports of the components.

**Comment by wmertens** [comment]
I just realized that of course the babel plugin only sees the `import()` statements and not their targets, so it can't change the target modules, unless we add an id string to every module, but then it's hard to know what the id will be, given an import statement. :-/

Perhaps the id should be a hash of the filesystem path at build time, and the Babel plugin should be configurable so it can map all `import()` statements to their target filesystem path?

Even if the system misses some import targets, it's not a problem since it gracefully degrades and it will never cause the client JS to fail.

**Comment by theKashey** [comment]
The only way is to use some webpack plugin, to get stats from webpack and work with them. This is the way [loadable-components](https://github.com/smooth-code/loadable-components) went since v3.
It's not doable with "extract-import" approach.

The nearest possibilities:
1. Scan the `imports.js` in search of chunks to be loaded. At least for CSS ones.
2. Don't worry any use [prerendered-component](https://github.com/theKashey/react-prerendered-component), which allows __not to wait__ for all the chunks loaded before hydration.

**Comment by theKashey** [comment]
That's sounds reasonable.
```js
const FILE_ID="RIC_hash(fileName)_CIR";// the same murmur hash, used to generate hash for imports
(function RIC_depotimization(a){})(FILE_ID) // to not let optimization to eat this variable
```
They use RegEx to find it among known chunks.

**Comment by theKashey** [comment]
For now, RIC might report used chunks and you might emit the right scripts.
How you will get "right" scripts - depends on the browser. There is a solution for `webpack`, for `parcel`, and in any case, it shall be external tool.
