### ISSUE TITLE
Provide defaults

### ISSUE THREAD

**Issue by wmertens** [theKashey/react-imported-component#44]
When I try wrapping the `importedComponent()` function so it provides a default LoadingComponent, it no longer marks.

Maybe there should be a `setDefaults` function?

**Comment by theKashey** [comment]
Could you elaborate more?

**Comment by wmertens** [comment]
I tried to do 

```js
import React from 'react'
import importedComponent from 'react-imported-component'
import Box from 'components/Layout/Box'

// The list of import mappings
try {
	require('app/imported-components')
} catch (err) {
	console.log('imported-components.js not found')
}

const DefaultLoading = props => <Box {...props}>…</Box>

export const makeSplitPoint = (fn, options) =>
	importedComponent(fn, {LoadingComponent: DefaultLoading, ...options})
```

but when I try to use it elsewhere by

```js
import {makeSplitPoint} from 'stuff'
const AsyncComponent = makeSplitPoint(() => import('./SomeComponent'))

const App () = => <AsyncComponent />
```

, it doesn't actually end up in the marks. I have to import directly from `react-imported-component`.

**Comment by theKashey** [comment]
Something is wrong. It was supported from(in?) the beginning.
Let me double check.

**Comment by wmertens** [comment]
Aha, I had to clear the Babel cache. Works great now! :+1:

**Comment by theKashey** [comment]
:hooray:
