### ISSUE TITLE
How to disable loading a component in SSR

### ISSUE THREAD

**Issue by wmertens** [theKashey/react-imported-component#47]
Some components I never want to render on the server, but I don't want to cause problems while rehydrating. What is the best way to do this?

**Comment by theKashey** [comment]
```js
class ClientSideOnly extends React.Component {
 state = {visible: false }
 componentDidMount() { this.setState({visible: true}) }
 render(){ return this.state.visible ? this.props.children: null;
}
}
```
PS: There is a special component for it - https://github.com/theKashey/react-prerendered-component#additional-api, but I just understand, that I did it wrong - it will not pass rehydrate.

**Comment by wmertens** [comment]
Ah of course, simple :)

I took a look at adding this to `Component.js` to avoid a wrapper component, but there's a lot going on in there and not sure how to do it cleanly. I was thinking that there could be a `ssr` option that defaults to `true`…

**Comment by theKashey** [comment]
(sorry, I am moving houses, and a bit offline)
This could be solved via composition - load some async component, which would render it's own internals only of FE, but would leave the mark. Probably HOC could help here.
```js
import('Component.js')
/// ...
export default clientSideComponent(MyComponent);
```

**Comment by theKashey** [comment]
see
https://github.com/theKashey/react-prerendered-component#client-side-only-components

**Comment by wmertens** [comment]
Hmm, I just noticed that even when using a wrapper, the component I do not wish to load in SSR gets interpreted.

I do

```js
import DefaultLoading from './components/Spinner'

export const makeSplitPoint = (fn, options) => {
	const Cmp = importedComponent(fn, {
		LoadingComponent: DefaultLoading,
		...options,
	})
	if (!options || options.ssr == null || options.ssr) return Cmp
	class NoSsr extends React.Component {
		state = {mounted: false}

		componentDidMount() {
			this.setState({mounted: true})
		}

		render() {
			return this.state.mounted ? <Cmp {...this.props} /> : false
		}
	}
	return NoSsr
}

// elsewhere
const GoogleLogin = makeSplitPoint(() => import('react-google-login'), {ssr: false}))
```

and I still get

**Comment by theKashey** [comment]
- you have to return `null` from a render, not `false`.
- but, anyway, it should not render it on SSR. Try to add some debug to render.

**Comment by wmertens** [comment]
@theKashey 	so it was always importing, I found the `noAutoImport` option.

I still think it would be much nicer if this was a built-in option into RIC.

```js

export const makeSplitPoint = (fn, options) => {
	const ssr = !options || options.ssr == null || options.ssr
	const noAutoImport = !ssr || options && options.noAutoImport
	const Cmp = importedComponent(fn, {
		LoadingComponent: DefaultLoading,
		...options,
		noAutoImport,
	})
	if (ssr) return Cmp
	class NoSsr extends React.Component {
		state = {mounted: false}

		componentDidMount() {
			this.setState({mounted: true})
		}

		render() {
			return this.state.mounted ? <Cmp {...this.props} /> : false
		}
	}
	return NoSsr
}
```

**Comment by theKashey** [comment]
`noAutoImport` is no more than nodejs behavior to auto import chunks before usage, and then be "ready" on the first render. In your example, it would be "read" on the second render.
From another point of view you are rendering "real" component after initial render, thus trashing layout. It's better to count on some global/context variable to "know" should you render "client-side-only" components or not.

**Comment by wmertens** [comment]
That said, there are some components that don't work on the server, because they need the DOM or they do extra work after mounting. For other components, you may decide that it's not necessary to SSR, for example because it will change anyway.

For those components, it would be great to turn off SSR altogether. The wrapper I show above does that, but it causes an extra component in the tree. It would be more efficient and less error-prone if this was built into imported-components. It took me a while to get the wrapper right.

For example for the issue https://github.com/react-dropzone/react-dropzone/issues/775 it would be nice to be able to say "Just do `const Cmp = imported(()=>import('react-dropzone'), {ssr: false})`".

**Comment by theKashey** [comment]
I tend to agree - having an easy way to control this feature is a good thing.

**Comment by theKashey** [comment]
In case of `react-dropzone` - I think it should _secure_ this moment by itself, not asking you to render it in a _right_ way.

**Comment by wmertens** [comment]
I'm sorry, I don't understand what you mean by secure and right?

**Comment by theKashey** [comment]
In terms of a “right” solution:
- you might use “browser” field in package json to ship something only to the browser
- or you may embed that “mounted” logic inside your component, to make it alive only in a real mount
- or you may wrap it with the code example above to do the same

....

- but not to use SSR:false on code splitting library, cos code splitting has nothing to do here. It’s not “right” “place” to fix.

**Comment by wmertens** [comment]
Current version: I inject `__PRERENDER__` in global while building the SSR code, and then the code is simply

```js
const NullComponent = () => null

export const makeSplitPoint = (fn, options) => {
	const ssr = !options || options.ssr == null || options.ssr
	if (global.__PRERENDER__ && !ssr) return NullComponent

	const noAutoImport =
		options && options.noAutoImport != null ? options.noAutoImport : !ssr
	return importedComponent(fn, {
		LoadingComponent: DefaultLoading,
		...options,
		noAutoImport,
	})
}
```

**Comment by theKashey** [comment]
I am finishing [version 6](https://github.com/theKashey/react-imported-component/pull/116), and if you have anything to add/change to the v5 you are using - be the change you seek.

**Comment by theKashey** [comment]
v6 has `toTrack` as well as `noImport` as a part of API. As well as a `client-side-only` magic comment.
