### ISSUE TITLE
possible bug with compressed class names?

### ISSUE THREAD

**Issue by krazyjakee** [theKashey/react-imported-component#5]
While trying to implement the material-ui library, I notice that SSR renders full css classes, while the client renders uglified classes.

In my fork I have added a demo but for the life of me can't figure out why the router won't reach it. If we can solve that problem first, I can perfect the bug example.

**Comment by theKashey** [comment]
"Loader" could not handle or solve this. It is just observer from some point of view.
Something is wrong with styles itself, maybe webpack loader is the reason - sometimes you have to "webpack" server code, to make it "fit" client code.

**Comment by krazyjakee** [comment]
I resolved it! It's worth noting that the server needs to be run with same NODE_ENV that the client is built. So in my case I set NODE_ENV to production when running the server and it fixed it.

**Comment by theKashey** [comment]
Glad to hear it.
PS: v4 has a SSR related bug, 4.0.1 is going to be released in 30 minutes.
