### ISSUE TITLE
back slash is not correct in Windows

### ISSUE THREAD

**Issue by lance75** [theKashey/react-imported-component#53]
the command "generate-imported-component" cannot run correctly under Windows, e.g. `5: () => import('..\HomePage')`, it should be replaced with slash - `5: () => import('./HomePage')`.

**Comment by theKashey** [comment]
Could you clarify a bit. It's _generate-imported-component produces windows specific code, with "windows slashes", while should keep "unix" paths?_.

**Comment by lance75** [comment]
> Could you clarify a bit? It's _generate-imported-component produces windows specific code, with "windows slashes", while should keep "unix" paths?_.

yes, you are right. the resulting JS file generated automatically has Windows backslash, like `..\HomePage`, but we want Unix style, `./HomePage`.

**Comment by theKashey** [comment]
It's a bit hard for me to test, so could I ask you for a little help?
Just change react-imported-component/dist/scanForImports.js, line 53:
```js
// (already transpiled code)
var getRelative = function getRelative(from, to) {
  var rel = (0, _path.relative)(from, to);
  if (rel[0] !== '.') {
    return '.' + _path.sep + rel;
  }
  // force unit-like paths
  return rel.split(_path.sep).join('/');
};
```

If that would work as expected(right) - we will resolve this issue.

**Comment by lance75** [comment]
> It's a bit hard for me to test, so could I ask you for a little help?
> Just change react-imported-component/dist/scanForImports.js, line 53:
> 
> ```js
> // (already transpiled code)
> var getRelative = function getRelative(from, to) {
>   var rel = (0, _path.relative)(from, to);
>   if (rel[0] !== '.') {
>     return '.' + _path.sep + rel;
>   }
>   // force unit-like paths
>   return rel.split(_path.sep).join('/');
> };
> ```
> 
> If that would work as expected(right) - we will resolve this issue.

after i changed line 56: `return '.' + _path.sep + rel;` to `rel = '.' + _path.sep + rel;` as well, everthing works well in my Windows 10. but i am not sure this is a general solution for all Windows users.

**Comment by lance75** [comment]
@theKashey  there is another potential issue:
when we run `scanForImport.js` each time, it will also scan the automatically generated JS file, such action rseults in a potential problem, the wrong imports will be appended into the JS file more and more. a possible soultion is that we can delete the old JS file during running the command `imported-components`.

**Comment by theKashey** [comment]
It does have "protection" from scanning itself. That protection does not work for windows due to the same `sep` issue. Ie `src/imported.js` !== `src\imported.js`

**Comment by theKashey** [comment]
Could you once again verify the changes?
