### ISSUE TITLE
back slash is not correct in Windows again

### ISSUE THREAD

**Issue by lance75** [theKashey/react-imported-component#69]
this is a reopen for an old issue - #53. After downloading the latest update, this issue comes back...

**Comment by theKashey** [comment]
Could you help me fix it?

**Comment by lance75** [comment]
by now, my solution is similar to what we did last time.
in the `/dist/cjs/scanners/shared.js` file, i replaced the statements from line54 ~ 59 with the code below:

var getRelative = function getRelative(from, to) {
  var rel = (0, _path.relative)(from, to);
  if (rel[0] !== '.') {
    rel = '.' + _path.sep + rel;
  }
  // force unix-like paths
  if (_path.sep === '\\') {
    return rel.split(_path.sep).join('/');
  }
  return rel;
};

**Comment by theKashey** [comment]
Sorry, but I could not figure out the difference between the current solution and your one. The current one should work as well, as your one does.

```js
export var getRelative = function getRelative(from, to) {
  // if path is not relative, this function does not a sence, just return the path.
  // we would not force "unix paths", but they should not exists here
  // could you try to comment out ony this line?
  if (/^[^./]/.test(to)) return to;

  // this function would force unix-like path
  var rel = normalizePath(relative(from, to));
  // this logic still the same. ('.'+sep).split.join === './'; 
  return rel[0] !== '.' ? './' + rel : rel;
```

The only place, where could be some error in early return statement, but it would lead to a problem only if original `to` contains windows separator, while it should not.

Could you help me once again?

**Comment by lance75** [comment]
> Sorry, but I could not figure out the difference between the current solution and your one. The current one should work as well, as your one does.
> 
> ```js
> export var getRelative = function getRelative(from, to) {
>   // if path is not relative, this function does not a sence, just return the path.
>   // we would not force "unix paths", but they should not exists here
>   // could you try to comment out ony this line?
>   if (/^[^./]/.test(to)) return to;
> 
>   // this function would force unix-like path
>   var rel = normalizePath(relative(from, to));
>   // this logic still the same. ('.'+sep).split.join === './'; 
>   return rel[0] !== '.' ? './' + rel : rel;
> ```y
> 
> The only place, where could be some error in early return statement, but it would lead to a problem only if original `to` contains windows separator, while it should not.
> 
> Could you help me once again?

you are right. everything works well if i comment out `if (/^[^./]/.test(to)) return to;`

**Comment by lance75** [comment]
![wrongslash_li](https://user-images.githubusercontent.com/14866709/53271186-a6fea000-36bb-11e9-9afa-e7da1169c35c.jpg)

each line in the above picture equals the variable "to", so they all passed your regex pattern and then returned.

**Comment by theKashey** [comment]
> everything works well if i comment out `if (/^[^./]/.test(to)) return to;`

That's all I need. Landing a patch....

**Comment by theKashey** [comment]
Ok, so the problem was with `resolve` applied before. What's why paths are absolute.
