### ISSUE TITLE
SSR not work when to execute JS using PhpExecJs

### ISSUE THREAD

**Issue by ekabolotina** [theKashey/react-imported-component#79]
Hello everyone, I very apologize if my question is too stupid. I followed the instructions in Readme, but my server.js is being executed from PHP by PhpExecJs, so 'detect-node' does not detect the environment as 'server side'. Could this be the reason that SSR is not working? Thank you!

**Comment by theKashey** [comment]
With easy. But it's more about "how it's not working". Is it node, or not, is not very crucial - it controls only auto imports and `LazyBoundary`.

First one would lead to empty components on the first render, but not on second (when they would be loaded)
Second would just throw.

So - could you explain how it does not work for you.

**Comment by theKashey** [comment]
(or provide some code, we all know php :) )

**Comment by ekabolotina** [comment]
Our backend uses the Symphony framework, so for SSR we use ReactBundle (https://github.com/Limenius/ReactBundle/blob/master/Resources/doc/index.md). I created a simple `Test` component and I want it to be a separate chunk, 
```
const Comp = importedComponent(() => import('./Test'), {
    LoadingComponent: () => <p>Load</p>,
    ErrorComponent: () => <p>Error</p>,
});

const App = () => (
    <>    
        <p>Hello</p>
        <Comp />
    </>
);
```
and then registered it with ReactOnRails
`ReactOnRails.register({App});`.
Then I just write in a twig template
```
<div id="root">
    {{ react_component('App') }}
  </div>
```.
My current goal is to get a rendered imported component using SSR. Therefore, I have disabled the rendering on the client for testing. This code when rendering on the server displays the following:
`<p>Hello</p>`.
What am I doing wrong?

**Comment by theKashey** [comment]
So it might display 3 different strings, but haven’t displayed any of them. And no exception were thrown. 

I’ll try play with React-on-rails and come out with the problem. To be honest the code itself is so straightforward, that I have no idea how it might not work 🤷‍♂️

**Comment by tbvjaos510** [comment]
I'm got a same issue. SSR works only on express server. It is well represented [here](https://github.com/tbvjaos510/react-imported-component-example)

**Comment by theKashey** [comment]
Thank you for the example to play with. Now I could solve the issue.

**Comment by tbvjaos510** [comment]
@theKashey Thanks. I hope it's fixed as soon as possible.

**Comment by theKashey** [comment]
Ok, so this is one of the _features_ of this library - it does not change how your code works. If you using dynamic `imports` - they still are dynamic, and you application would require a few ticks to load.
There is also a command to await for such events - `whenComponentsReady`. It's documented, but there is no clear usage for it provided. 

Correct code would be:
```js
import React from "react";
import ReactDOM from "react-dom/server";
import {StaticRouter} from "react-router-dom";
import App from "./App";
import {printDrainHydrateMarks, whenComponentsReady} from "react-imported-component";

// await whenComponentsReady(); // for top level await enabled systems

whenComponentsReady().then(() => {
  const markup =
    ReactDOM.renderToString(
      <StaticRouter location={"/codeSplit"} context={{}}>
        <App/>
      </StaticRouter>
    ) + printDrainHydrateMarks();
  console.log(markup);
});
```

Keep in mind - this code is asynchronies, unless you use to [synchronously await](https://github.com/abbr/deasync) (nodejs one) for a promise returned from `whenComponentsReady` .

**Comment by tbvjaos510** [comment]
It seems to update [README](https://github.com/theKashey/react-imported-component#ssr-server-side-rendering) page. Thank you for your quick answer.
