### ISSUE TITLE
props being sent down to child

### ISSUE THREAD

**Issue by lifeiscontent** [theKashey/react-imported-component#8]
is there a way to not expose the props of a loadable component to a component?

my example is I've got a bunch of icons and the only props I care about are width/height/fill color and react is complaining about there being extra props on the SVG element that it doesn't know about.

**Comment by theKashey** [comment]
Display SVG with some props, or just consume some space while it loading....
```js
const Icon = imported( () => import('./Icon.svg'), {
 render: (Icon, state, {width,height,color}) => icon ? <Icon width={width}  height={height}  color={color} /> : <div style={{display:'inline-block', width, height}} />
});
```
`render` prop come with latest release, 10 minutes ago.

**Comment by lifeiscontent** [comment]
@theKashey so in the case of using a factory what would that look like?

```jsx
import importedComponent from 'react-imported-component';
import Loader from './Loader';
const importFactory = importFunction => importedComponent(importFunction, {
  render: (Component, state, props) => Component ? <Component {...props} /> : <Loader />
}); 
```

**Comment by theKashey** [comment]
Yep, just dont forget to get only props you want, not the all possible.

**Comment by lifeiscontent** [comment]
@theKashey thanks!
